config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books
  resources :reviews 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ActiveRecord::Base
    
    belongs_to :reviews
    has_many :users, through: :reviews 

    has_attached_file :book_img, styles: { book_index: "250x350>", book_show: "325x475>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :book_img, content_type: /\Aimage\/.*\z/

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user_id
  belongs_to :book_id
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :reviews
  has_many :books, through: :reviews 

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

    before_action :find_book, only: [:show, :edit, :update, :destroy]
    def index
        @books = Book.all.order("created_at DESC")
    end

    def show
    end

    def new
        @book = Book.new
    end

    def create
        @book = Book.new(book_params)
        if @book.save
            redirect_to books_path
        end 
    end

    def edit
    end

    def update
        if @book.update(book_params)
        redirect_to book_path(@book)
        
        else
            render 'edit'
        end

    end

    def destroy
        @book.destroy
        redirect_to books_path
    end


    private

    def book_params
        params.require(:book).permit(:title, :description, :author, :book_img)
    end

    def find_book
        @book = Book.find(params[:id])
    end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    def index
        @reviews = Review.all
    end

    def show
        @review = Review.find(params[:id])
    end

    def new
        @review = Review.new
    end

    def create
        @review = Review.create(review_params)
    end

    def edit
    end

    def update
    end

    def review_params
        params.require(:review).permit(:rating, :comment, :book_d, :user_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/genre_helper.rb
module GenreHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/views/books/_form.html.erb
<%= simple_form_for @book do |f| %>
	<%= f.file_field :book_img %>
	<%= f.input :title, label: "Book Title" %>
	<%= f.input :description %>
	<%= f.input :author %>
	<%= f.button :submit %>
<% end %>

app/views/books/edit.html.erb
<%= render 'form' %>

app/views/books/index.html.erb
<% @books.each do |book| %>
    <a href= "/books/<%= book.id %>">
    <%= image_tag book.book_img.url(:book_index) %>
    </a>
<% end %>

app/views/books/new.html.erb
<h3>New Book</h3>

<%= render 'form' %>

<%= link_to "Go Back", books_path %>

app/views/books/show.html.erb
<h2><%= @book.title %></h2>
<h3><%= @book.author %></h2>
<p><%= @book.description %><p>

<%= link_to "Edit", edit_book_path(@book) %>
<%= link_to "Delete", book_path(@book), method: :delete, data: {confirm: "Are you sure?"} %>

<%= link_to "Go Back", books_path %>

<%= link_to "Write a review", new_review_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookReviewApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <nav class= "navbar navbar-default">
    <div class = "container">
    <div class = "navbar-header">
    <%= link_to "BookBarn", books_path, class: 
    "navbar-brand" %>
    </div>
    <ul class="nav navbar-nav">
      <li><%= link_to "Sign up", new_user_registration_path%></li>
      <% if user_signed_in? %>
      <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
      <% else %>
      <li><%= link_to "Log In", new_user_session_path %><li>
      <% end %>
    </ul>

    <ul class ="nav navbar-nav navbar right" >
    <% if user_signed_in? %>
    <li><%=link_to "Add a book!", new_book_path %></li>
    <% end %>
    </div>
    </nav>


    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/reviews/index.html.erb
<% @reviews.each do |review| %>
<ul>
</li><%= review.comment %></li>
</ul>
<% end %>

app/views/reviews/new.html.erb
<%= simple_form_for @review do |f| %>
	<%= f.collection_select :book_id, Book.all, :id, :title %>
	<%= f.collection_select :user_id, User.all, :id, :email %>
	<%= f.input :rating, label: "Book Rating" %>
	<%= f.input :comment %>
	<%= f.button :submit %>
<% end %>

<%= link_to "Go Back", books_path %>